version: "3.3"
services:
  walletkit:
    image: waltid/walletkit:latest  # backend docker image
    command:
      - run
    environment:
      WALTID_DATA_ROOT: ./data-root
      WALTID_WALLET_BACKEND_BIND_ADDRESS: 0.0.0.0
      EXTERNAL_HOSTNAME: $HOSTNAME$COMPUTERNAME
    volumes:
      - .:/app/data-root # data store volume incl. config files.
    extra_hosts:
      - "$HOSTNAME$COMPUTERNAME:host-gateway"
  wallet-ui:
    image: waltid/ssikit-web-wallet:latest # wallet web ui docker image
  verifier-ui:
    image: waltid/ssikit-verifier-portal:latest # verifier web ui docker image
  issuer-ui:
    image: waltid/ssikit-issuer-portal:latest # issuer web ui docker image
  ingress:
    image: nginx:1.15.10-alpine
    ports:
      - target: 80
        published: 8080 # wallet ui publish port
        protocol: tcp
        mode: host
      - target: 81
        published: 8081 # verifier ui publish port
        protocol: tcp
        mode: host
      - target: 82
        published: 8082 # issuer ui publish port
        protocol: tcp
        mode: host
    volumes:
      - ./ingress.conf:/etc/nginx/conf.d/default.conf # API gateway configuration
